%YAML:1.0
# 数据库根目录位置：该目录下应该有rgb_index/和dep_index/两个文件夹，记录了rgb图与深度度
data_source: /home/y/code/dataset/slam
# 图像特征的检测算子与描述算子的名称
detector_name: SIFT
descriptor_name: SIFT
# 数据的起始编号与结束编号
start_index: 1
end_index: 2001
# 是否在灰度图中处理数据：暂不支持颜色信息
grayscale: yes
# 最小匹配距离
match_min_dist: 5
# 每一次循环的等待时间（毫秒）
step_time: 0

# feature manager
#连续看见多少帧则记录至仓库
save_if_seen: 1
# 新特征，未连续出现多少帧则从缓存删除
del_not_seen: 3
# 是否为没有深度数据的点设置最大深度
set_max_depth: yes
# 最大深度
max_depth: 20
# 每一帧最最多匹配的路标上限
max_landmark_per_loop: 100

# pose graph
# 优化步数
optimize_step: 10
# robust核函数
robust_kernel: Cauchy
# 最大位移，超过此位移后需要全局优化
max_pos_change: 0.2
